ALTER TABLE mir12component  CONVERT TO CHARACTER SET utf8;
ALTER TABLE mir13link_employee_project  CONVERT TO CHARACTER SET utf8;
ALTER TABLE mir14jiraworklog  CONVERT TO CHARACTER SET utf8;
ALTER TABLE mir15invoice  CONVERT TO CHARACTER SET utf8;

ALTER DATABASE retra charset=utf8;